[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50

[theme]
primaryColor = "#0284c7"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
font = "sans serif"

[browser]
gatherUsageStats = false
